export const ACTION_LOGIN = 'LOGGEDIN';
export const ACTION_LOGOUT = 'LOGOUT';

// ROOM actions
export const ACTION_STORE_ROOM = 'ACTION_STORE_ROOM';
export const ACTION_STORE_ROOMS = 'ACTION_STORE_ROOMS';
export const ACTION_UPDATE_ROOM = 'ACTION_UPDATE_ROOM';
export const ACTION_DESTROY_ROOM = 'ACTION_DESTROY_ROOM';

// PROFILE actions
export const ACTION_STORE_PROFILE = 'ACTION_STORE_PROFILE';
export const ACTION_UPDATE_PROFILE = 'ACTION_UPDATE_PROFILE';
export const ACTION_DESTROY_PROFILE = 'ACTION_DESTROY_PROFILE';

// Peer actions
export const ACTION_STORE_PEER = 'ACTION_STORE_PEER';
export const ACTION_UPDATE_PEER = 'ACTION_UPDATE_PEER';
export const ACTION_DESTROY_PEER = 'ACTION_DESTROY_PEER';

// Mood actions
export const ACTION_STORE_MOOD = 'ACTION_STORE_MOOD';
export const ACTION_UPDATE_MOOD = 'ACTION_UPDATE_MOOD';
export const ACTION_DESTROY_MOOD = 'ACTION_DESTROY_MOOD';

// Mood actions
export const ACTION_STORE_MOODS = 'ACTION_STORE_MOODS';
export const ACTION_UPDATE_MOODS = 'ACTION_UPDATE_MOODS';
export const ACTION_DESTROY_MOODS = 'ACTION_DESTROY_MOODS';

